      # Depending on the order that Standby databases have been added to the configuation it is possible that the Active Target is not the same as the first one
      # specified by FastStartFailoverTarget.    If this is the case then it needs to be corrected, so that the preferred failover target is used.
        
      - name: Get Current Active Target
        shell: |
              . ~/.bash_profile
               dgmgrl -silent / "show fast_start failover;" | awk '/Active Target:/{print $3}'
        register: get_active_target
        delegate_to: "{{ delegation_host }}"
        changed_when: false

      - name: Change Active Target
        when: preferred_active_target != ( get_active_target.stdout | lower | trim )
        block:

          - name: Set Preferred Active Target
            shell: |
                  . ~/.bash_profile
                  dgmgrl -silent / "set fast_start failover target to {{ preferred_active_target }};"
            delegate_to: "{{ delegation_host }}"
       
          # It takes a little while for the Active target to change so poll for this
          - name: Check Change to Active Target
            shell: |
                  . ~/.bash_profile
                  dgmgrl -silent / "show fast_start failover;" | awk '/Active Target:/{print $3}'
            register: get_new_active_target
            delegate_to: "{{ delegation_host }}"
            changed_when: false
            retries: 20
            delay: 20
            until: preferred_active_target == ( get_new_active_target.stdout | lower | trim )