
- name: (main/set-primary-dgbroker) Configure Oracle Data Guard broker on primary
  copy:
    src: "{{ role_path}}/files/setup_primary_dgbroker.sh"
    dest: "/tmp/setup_primary_dgbroker.sh"
    mode: 0744
  become: true
  become_user: "{{ rdbms_service_user.name }}"

- name: (main/set-primary-dgbroker) Run Oracle Data Guard script for standby 
  shell: ". ~/.bash_profile; /tmp/setup_primary_dgbroker.sh -t {{ database_primary_unique_name }} -s {{ database_standby_unique_name }}"
  become: true
  become_user: "{{ rdbms_service_user.name }}"
  register: dg_result
  failed_when: dg_result.rc != 0