- name: Check Credential Exists in Wallet
  shell: |
    . ~/.bash_profile
    mkstore -wrl {{ wallet_dir }} -listCredential | grep -c ": {{ credential_name }} sys$" | cat
  register: get_credential_name_in_wallet
  changed_when: false

- name: If Credential Exists then Check that it Works
  shell: |
    . ~/.bash_profile
    echo exit | sqlplus -S -L /@{{ credential_name }} as sysdba
  register: check_password
  ignore_errors: True
  when: ( get_credential_name_in_wallet.stdout | int ) > 0
  changed_when: false

- name: Update Existing Wallet Credentials with New Password
  shell: |
    . ~/.bash_profile
    mkstore -wrl {{ wallet_dir }} -modifyCredential {{ credential_name }} sys ${SYS_PASSWORD}
  environment:
    SYS_PASSWORD: "{{ sys_password }}"
  when:
    - ( get_credential_name_in_wallet.stdout | int ) > 0
    - ( check_password.rc | default(1)) > 0
