- name: Check Credential Exists in Wallet
  shell: |
    . ~/.bash_profile
    mkstore -wrl {{ wallet_dir }} -listCredential | grep -c ": {{ credential_name }} sys$" | cat
  register: get_credential_name_in_wallet
  changed_when: false

- name: Update Existing Credentials
  when: ( get_credential_name_in_wallet.stdout | int ) > 0
  block:

        - name: If Credential Exists then Check that it Works
          shell: |
            . ~/.bash_profile
            echo exit | sqlplus -S -L /@{{ credential_name }} as sysdba
          register: check_password
          ignore_errors: True
          changed_when: false

        - name: Update Existing Wallet Credentials with New Password
          shell: |
            . ~/.bash_profile
            mkstore -wrl {{ wallet_dir }} -modifyCredential {{ credential_name }} sys ${SYS_PASSWORD}
          environment:
            SYS_PASSWORD: "{{ sys_password }}"
          when: ( check_password.rc | default(1)) > 0

        - name: Increment Update Password Count
          set_fact:
            password_update_count: "{{ ( password_update_count | int ) + 1 }}"
          when: ( check_password.rc | default(1)) > 0

- name: Add New Credentials
  when: ( get_credential_name_in_wallet.stdout | int ) == 0
  block:

        - name: Add Database Credentials to Wallet
          shell: |
                . ~/.bash_profile
                mkstore -wrl {{ wallet_dir }} -createCredential {{ credential_name }} sys ${SYS_PASSWORD}
          when: ( database_in_wallet.stdout | int ) == 0
          environment:
            SYS_PASSWORD: "{{ sys_password }}"